from sis.reports.quote_diagnostics import QuoteDiagnostic
from sis.reports.quote_diagnostics_markdown import quote_diagnostics_report_lines


def test_quote_diagnostics_report_lines_renders_populated_report() -> None:
    diagnostic = QuoteDiagnostic(
        venue="gtrade",
        symbol="SPY",
        stale_threshold_ms=3000,
        rows=2,
        market_open_rows=1,
        tradable_rate=0.5,
        stale_rate=0.25,
        missing_mark_price_rate=0.0,
        missing_index_price_rate=0.0,
        missing_oracle_price_rate=0.5,
        missing_funding_rate=1.0,
        missing_open_interest_rate=1.0,
        missing_spread_rate=0.0,
        l2_only_rate=0.0,
        fee_mode_unknown_rate=0.5,
        block_reason_distribution={"stale": 1},
        stale_missing_oracle_ts_rate=0.0,
        stale_old_oracle_ts_rate=0.25,
        market_status_unknown_rate=0.0,
        market_closed_rate=0.5,
        oracle_age_p50_ms=100,
        oracle_age_p90_ms=200,
        spread_p50_bps=1.5,
        spread_p90_bps=2.5,
    )
    lines = quote_diagnostics_report_lines(
        diagnostics=[diagnostic],
        summary={
            "diagnostic_count": 1,
            "row_count": 2,
            "venues": ["gtrade"],
            "symbols": ["SPY"],
            "quick_navigation": {"quote_diagnostics_report": "data/reports/quote.md"},
            "related_reports": {"current_state_index_report": "data/reports/current.md"},
        },
        venue="gtrade",
        symbol="SPY",
    )

    assert lines == [
        "# Quote Diagnostics Report",
        "",
        "## Quick Navigation",
        "",
        "- quote_diagnostics_report: data/reports/quote.md",
        "",
        "## Related Reports",
        "",
        "- current_state_index_report: data/reports/current.md",
        "",
        "## Summary",
        "",
        "- diagnostic_count: 1",
        "- row_count: 2",
        "- venues: ['gtrade']",
        "- symbols: ['SPY']",
        "- filter_venue: gtrade",
        "- filter_symbol: SPY",
        "",
        "## Diagnostics",
        "",
        "- venue=gtrade symbol=SPY",
        "  - stale_threshold_ms: 3000",
        "  - rows: 2",
        "  - market_open_rows: 1",
        "  - tradable_rate: 0.5000",
        "  - stale_rate: 0.2500",
        "  - missing_mark_price_rate: 0.0000",
        "  - missing_index_price_rate: 0.0000",
        "  - missing_oracle_price_rate: 0.5000",
        "  - missing_funding_rate: 1.0000",
        "  - missing_open_interest_rate: 1.0000",
        "  - missing_spread_rate: 0.0000",
        "  - l2_only_rate: 0.0000",
        "  - fee_mode_unknown_rate: 0.5000",
        "  - block_reason_distribution: {'stale': 1}",
        "  - oracle_age_p50_ms: 100",
        "  - oracle_age_p90_ms: 200",
        "  - spread_p50_bps: 1.5",
        "  - spread_p90_bps: 2.5",
    ]


def test_quote_diagnostics_report_lines_renders_empty_report() -> None:
    lines = quote_diagnostics_report_lines(
        diagnostics=[],
        summary={
            "diagnostic_count": 0,
            "row_count": 0,
            "venues": [],
            "symbols": [],
            "quick_navigation": {},
            "related_reports": {},
        },
        venue=None,
        symbol=None,
    )

    assert lines == [
        "# Quote Diagnostics Report",
        "",
        "## Summary",
        "",
        "- diagnostic_count: 0",
        "- row_count: 0",
        "- venues: []",
        "- symbols: []",
        "- filter_venue: None",
        "- filter_symbol: None",
        "",
        "## Diagnostics",
        "",
        "- diagnostics: none",
    ]
