from __future__ import annotations

BACKTEST_KILL_GATE_SCHEMA_VERSION = "backtest_kill_gate.v1"
CANDIDATE_PROTOCOL_MANIFEST_SCHEMA_VERSION = "candidate_protocol_manifest.v1"
EDGE_CANDIDATE_FACTORY_SUMMARY_SCHEMA_VERSION = "edge_candidate_factory_summary.v1"
PROFIT_CORE_ACTUAL_CASH_READINESS_PACKET_SCHEMA_VERSION = (
    "profit_core_actual_cash_readiness_packet.v1"
)
PROFIT_CORE_ACTUAL_CASH_REPORT_GATE_SCHEMA_VERSION = "profit_core_actual_cash_report_gate.v1"
PROFIT_CORE_ADVERSARIAL_REVIEW_SCHEMA_VERSION = "profit_core_adversarial_review.v1"
PROFIT_CORE_EVIDENCE_PACKET_SCHEMA_VERSION = "profit_core_evidence_packet.v1"
PROFIT_CORE_EXTERNAL_VENUE_ADAPTER_RUN_SCHEMA_VERSION = "profit_core_external_venue_adapter_run.v1"
PROFIT_CORE_FEEDBACK_THRESHOLD_CALIBRATION_SCHEMA_VERSION = (
    "profit_core_feedback_threshold_calibration.v1"
)
PROFIT_CORE_RISK_TAKER_SPRINT_ISOLATION_SCHEMA_VERSION = (
    "profit_core_risk_taker_sprint_isolation.v1"
)
PROFIT_CORE_TINY_ACTUAL_CASH_MEASUREMENT_SCHEMA_VERSION = (
    "profit_core_tiny_actual_cash_measurement.v1"
)
TRIAL_MULTIPLICITY_ACCOUNT_SCHEMA_VERSION = "trial_multiplicity_account.v1"
VIRTUAL_EXECUTION_GATE_SCHEMA_VERSION = "virtual_execution_gate.v1"

__all__ = [
    "BACKTEST_KILL_GATE_SCHEMA_VERSION",
    "CANDIDATE_PROTOCOL_MANIFEST_SCHEMA_VERSION",
    "EDGE_CANDIDATE_FACTORY_SUMMARY_SCHEMA_VERSION",
    "PROFIT_CORE_ACTUAL_CASH_READINESS_PACKET_SCHEMA_VERSION",
    "PROFIT_CORE_ACTUAL_CASH_REPORT_GATE_SCHEMA_VERSION",
    "PROFIT_CORE_ADVERSARIAL_REVIEW_SCHEMA_VERSION",
    "PROFIT_CORE_EVIDENCE_PACKET_SCHEMA_VERSION",
    "PROFIT_CORE_EXTERNAL_VENUE_ADAPTER_RUN_SCHEMA_VERSION",
    "PROFIT_CORE_FEEDBACK_THRESHOLD_CALIBRATION_SCHEMA_VERSION",
    "PROFIT_CORE_RISK_TAKER_SPRINT_ISOLATION_SCHEMA_VERSION",
    "PROFIT_CORE_TINY_ACTUAL_CASH_MEASUREMENT_SCHEMA_VERSION",
    "TRIAL_MULTIPLICITY_ACCOUNT_SCHEMA_VERSION",
    "VIRTUAL_EXECUTION_GATE_SCHEMA_VERSION",
]
