from __future__ import annotations

from decimal import Decimal

CRYPTO_PERP_PROJECT_COST_MODEL_ID = "crypto_perp_project_cost_assumption_v1"
CRYPTO_PERP_CONSERVATIVE_COST_MODEL_ID = "crypto_perp_conservative_stress_assumption_v1"

CRYPTO_PERP_PROJECT_TAKER_FEE_RATE = Decimal("0.0004")
CRYPTO_PERP_PROJECT_FUNDING_RATE = Decimal("0.0001")
CRYPTO_PERP_PROJECT_SLIPPAGE_BPS = Decimal("2")
CRYPTO_PERP_STRESS_SLIPPAGE_MULTIPLIER = Decimal("2")
CRYPTO_PERP_CONSERVATIVE_TAKER_FEE_RATE = Decimal("0.0006")

CRYPTO_PERP_PROJECT_TAKER_FEE_RATE_TEXT = str(CRYPTO_PERP_PROJECT_TAKER_FEE_RATE)
CRYPTO_PERP_PROJECT_FUNDING_RATE_TEXT = str(CRYPTO_PERP_PROJECT_FUNDING_RATE)
CRYPTO_PERP_PROJECT_SLIPPAGE_BPS_TEXT = str(CRYPTO_PERP_PROJECT_SLIPPAGE_BPS)
