from __future__ import annotations

from pathlib import Path

import polars as pl


def build_initial_cost_matrix(out_path: Path) -> None:
    rows = [
        {
            "venue": "gtrade",
            "symbol": "SPY",
            "asset_class": "index",
            "open_fee_bps": 5,
            "close_fee_bps": 5,
            "spread_p50_bps": None,
            "spread_p90_bps": None,
            "spread_p99_bps": None,
            "holding_cost_4h_bps": None,
            "holding_cost_24h_bps": None,
            "holding_cost_72h_bps": None,
            "stale_rate": None,
            "tradable_rate": None,
            "notes": "spreadP requires live probe",
        },
        {
            "venue": "gtrade",
            "symbol": "QQQ",
            "asset_class": "index",
            "open_fee_bps": 5,
            "close_fee_bps": 5,
            "spread_p50_bps": None,
            "spread_p90_bps": None,
            "spread_p99_bps": None,
            "holding_cost_4h_bps": None,
            "holding_cost_24h_bps": None,
            "holding_cost_72h_bps": None,
            "stale_rate": None,
            "tradable_rate": None,
            "notes": "spreadP requires live probe",
        },
        {
            "venue": "gtrade",
            "symbol": "XAU",
            "asset_class": "commodity",
            "open_fee_bps": 5,
            "close_fee_bps": 5,
            "spread_p50_bps": None,
            "spread_p90_bps": None,
            "spread_p99_bps": None,
            "holding_cost_4h_bps": None,
            "holding_cost_24h_bps": None,
            "holding_cost_72h_bps": None,
            "stale_rate": None,
            "tradable_rate": None,
            "notes": "fixed spread 1 bps; holding/borrowing requires live probe",
        },
        {
            "venue": "ostium",
            "symbol": "SPX_EQUIV",
            "asset_class": "index",
            "open_fee_bps": None,
            "close_fee_bps": None,
            "spread_p50_bps": None,
            "spread_p90_bps": None,
            "spread_p99_bps": None,
            "holding_cost_4h_bps": None,
            "holding_cost_24h_bps": None,
            "holding_cost_72h_bps": None,
            "stale_rate": None,
            "tradable_rate": None,
            "notes": "requires probe",
        },
        {
            "venue": "ostium",
            "symbol": "NDX_EQUIV",
            "asset_class": "index",
            "open_fee_bps": None,
            "close_fee_bps": None,
            "spread_p50_bps": None,
            "spread_p90_bps": None,
            "spread_p99_bps": None,
            "holding_cost_4h_bps": None,
            "holding_cost_24h_bps": None,
            "holding_cost_72h_bps": None,
            "stale_rate": None,
            "tradable_rate": None,
            "notes": "requires probe",
        },
        {
            "venue": "ostium",
            "symbol": "XAU",
            "asset_class": "commodity",
            "open_fee_bps": None,
            "close_fee_bps": None,
            "spread_p50_bps": None,
            "spread_p90_bps": None,
            "spread_p99_bps": None,
            "holding_cost_4h_bps": None,
            "holding_cost_24h_bps": None,
            "holding_cost_72h_bps": None,
            "stale_rate": None,
            "tradable_rate": None,
            "notes": "requires probe",
        },
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pl.DataFrame(rows).write_csv(out_path)

