from __future__ import annotations

from sis.reports import audit_summary_normalizers as _audit_summary
from sis.reports import execution_status_normalizers as _execution_status
from sis.reports import execution_lineage_normalizers as _execution_lineage
from sis.reports import phase_gate_summary_normalizers as _phase_gate_summary
from sis.reports import remediation_recommendation_normalizers as _remediation_recommendation

all_latest_execution_lineage_fields = _execution_lineage.all_latest_execution_lineage_fields
defaulted_all_latest_execution_lineage_fields = (
    _execution_lineage.defaulted_all_latest_execution_lineage_fields
)
execution_comparison_flat_fields = _execution_lineage.execution_comparison_flat_fields
execution_snapshot_flat_fields = _execution_lineage.execution_snapshot_flat_fields
first_remapped_latest_execution_lineage_fields = (
    _execution_lineage.first_remapped_latest_execution_lineage_fields
)
latest_execution_flat_lines = _execution_lineage.latest_execution_flat_lines
latest_execution_flat_section_lines = _execution_lineage.latest_execution_flat_section_lines
latest_execution_flat_sections = _execution_lineage.latest_execution_flat_sections
latest_execution_lineage_fields = _execution_lineage.latest_execution_lineage_fields
latest_execution_lineage_fields_from_payload = (
    _execution_lineage.latest_execution_lineage_fields_from_payload
)
latest_execution_lineage_fields_from_summary = (
    _execution_lineage.latest_execution_lineage_fields_from_summary
)
latest_execution_lineage_flat_lines = _execution_lineage.latest_execution_lineage_flat_lines
latest_execution_lineage_from_notes = _execution_lineage.latest_execution_lineage_from_notes
latest_execution_lineage_from_values = _execution_lineage.latest_execution_lineage_from_values
latest_execution_lineage_payload = _execution_lineage.latest_execution_lineage_payload
latest_execution_lineage_payload_from_summary = (
    _execution_lineage.latest_execution_lineage_payload_from_summary
)
latest_execution_payload_and_fields_from_summary = (
    _execution_lineage.latest_execution_payload_and_fields_from_summary
)
latest_execution_section_lines = _execution_lineage.latest_execution_section_lines
latest_execution_sections = _execution_lineage.latest_execution_sections
merged_latest_execution_lineage_fields = _execution_lineage.merged_latest_execution_lineage_fields
merged_latest_execution_payload_and_fields = (
    _execution_lineage.merged_latest_execution_payload_and_fields
)
merged_remapped_latest_execution_lineage_fields = (
    _execution_lineage.merged_remapped_latest_execution_lineage_fields
)
normalize_execution_comparison_summary = _execution_lineage.normalize_execution_comparison_summary
normalize_execution_snapshot_summary = _execution_lineage.normalize_execution_snapshot_summary
remap_latest_execution_lineage_fields = _execution_lineage.remap_latest_execution_lineage_fields
execution_diagnostics_flat_fields = _execution_status.execution_diagnostics_flat_fields
execution_drift_overview_flat_fields = _execution_status.execution_drift_overview_flat_fields
execution_gap_history_flat_fields = _execution_status.execution_gap_history_flat_fields
execution_snapshot_drift_flat_fields = _execution_status.execution_snapshot_drift_flat_fields
execution_state_comparison_flat_fields = _execution_status.execution_state_comparison_flat_fields
normalize_execution_diagnostics_summary = _execution_status.normalize_execution_diagnostics_summary
normalize_execution_drift_overview_summary = (
    _execution_status.normalize_execution_drift_overview_summary
)
normalize_execution_gap_history_summary = _execution_status.normalize_execution_gap_history_summary
normalize_execution_snapshot_drift_summary = (
    _execution_status.normalize_execution_snapshot_drift_summary
)
normalize_execution_state_comparison_summary = (
    _execution_status.normalize_execution_state_comparison_summary
)
audit_dashboard_flat_fields = _audit_summary.audit_dashboard_flat_fields
audit_bundle_flat_fields = _audit_summary.audit_bundle_flat_fields
audit_summary_fields = _audit_summary.audit_summary_fields
audit_timeline_flat_fields = _audit_summary.audit_timeline_flat_fields
audit_bundle_history_flat_fields = _audit_summary.audit_bundle_history_flat_fields
ops_review_flat_fields = _audit_summary.ops_review_flat_fields
normalize_phase_gate_summary = _phase_gate_summary.normalize_phase_gate_summary
normalize_readiness_summary = _phase_gate_summary.normalize_readiness_summary
phase_gate_flat_fields = _phase_gate_summary.phase_gate_flat_fields
phase_gate_nested_fields = _phase_gate_summary.phase_gate_nested_fields
phase_gate_issue_preview_lines = _phase_gate_summary.phase_gate_issue_preview_lines
phase_gate_issue_note_previews = _phase_gate_summary.phase_gate_issue_note_previews
phase_gate_issue_note_lines = _phase_gate_summary.phase_gate_issue_note_lines
readiness_flat_fields = _phase_gate_summary.readiness_flat_fields
compare_signal_snapshots = _remediation_recommendation.compare_signal_snapshots
source_confidence_for_observed_sources = (
    _remediation_recommendation.source_confidence_for_observed_sources
)
signal_observed_sources_by_reason = _remediation_recommendation.signal_observed_sources_by_reason
signal_source_confidence = _remediation_recommendation.signal_source_confidence
recommend_remediation_actions = _remediation_recommendation.recommend_remediation_actions
